clive:
    images: iqa/CLIVE/images
    saliency_maps: iqa/CLIVE/saliency_maps
    data: iqa/CLIVE/data.csv
koniq10k:
    images: iqa/koniq10k/images
    saliency_maps: iqa/koniq10k/saliency_maps
    data: iqa/koniq10k/data.csv

image_shape:
    - 384
    - 512

saliency_shape:
    - 12
    - 16

max_epochs: 30  
batch_size: 16
num_workers: 16
learning_rate_head: 3.0e-4
learning_rate_backbone: 3.0e-5
alpha_sal: 0.2

saliency_type: mult

model_checkpoint_best:
    monitor: val_srocc
    mode: max
    save_top_k: 1
    save_weights_only: True
    verbose: True

model_checkpoint_last:
    save_weights_only: True
    verbose: True

early_stopping:
    monitor: val_srocc
    mode: max
    patience: 8
    verbose: True

lr_scheduler:
    step_size: 7
    gamma: 0.1
    verbose: True


lr_dict:
    interval: epoch
    frequency: 1
    # monitor: val/srocc
