# ==== constants ====

saliency_type: multiple_concat_fusion_pretrained

max_epochs: 10  
batch_size: 16
num_workers: 16
lr_head: 3.0e-5
lr_backbone: 3.0e-6
lr_concat_convs: 3.0e-7

weights_pretrained: /home/26a_kir@lab.graphicon.ru/experiments-with-saliency/checkpoints/best_date=2023-02-12_14:11_val_srocc=0.892_epoch=22.ckpt

# ==== pytorch_lighting settings ====

model_checkpoint_best:
    monitor: val_srocc
    mode: max
    save_top_k: 1
    save_weights_only: True.0
    verbose: True

model_checkpoint_last:
    save_weights_only: True
    verbose: True

early_stopping:
    monitor: val_srocc
    mode: max
    patience: 8
    verbose: True

lr_scheduler:
    step_size: 7
    gamma: 0.1
    verbose: True


lr_dict:
    interval: epoch
    frequency: 1
    # monitor: val/srocc

# ==== datasets ====

clive:
    images: iqa/CLIVE/images
    saliency_maps: iqa/CLIVE/saliency_maps
    data: iqa/CLIVE/data.csv
koniq10k:
    images: iqa/koniq10k/images
    saliency_maps: iqa/koniq10k/saliency_maps
    data: iqa/koniq10k/data.csv

image_shape:
    - 384
    - 512

saliency_shape:
    - 384
    - 512